<a href="https://colab.research.google.com/github/jasskarannn/artifial_neural_network_IITK/blob/master/ANN_iitk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataset = pd.read_csv('./Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
X[:,2] = labelEncoder.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
print(X_train)

[[ 0.996257   -0.57561821 -0.57619557 ...  0.64706357  0.96245432
  -0.57185769]
 [ 0.996257   -0.57561821 -0.57619557 ...  0.64706357 -1.03901035
  -0.55666653]
 [ 0.996257   -0.57561821 -0.57619557 ...  0.64706357 -1.03901035
  -1.37966849]
 ...
 [-1.00375706  1.73726261 -0.57619557 ...  0.64706357  0.96245432
   0.46420045]
 [-1.00375706 -0.57561821  1.73552185 ...  0.64706357  0.96245432
   1.7082806 ]
 [ 0.996257   -0.57561821 -0.57619557 ...  0.64706357 -1.03901035
   1.05040606]]


In [9]:
import keras
from keras.models import Sequential
from keras.layers import Dense


In [18]:
classifier = Sequential()
classifier.add(Dense(units=6, activation='relu'))
classifier.add(Dense(units=6, activation='relu'))
classifier.add(Dense(units=6, activation='relu'))
classifier.add(Dense(units=6, activation='relu'))
classifier.add(Dense(units=1, activation='sigmoid'))

classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy']) #simple gradient descent
classifier.fit(X_train, y_train, epochs=200)

y_pred = classifier.predict(X_test)
y_pred = (y_pred>0.5) # if probability >50% y_pred is 1 else 0


Epoch 1/200
8000/8000 [==============================] - 1s 67us/step - loss: 0.5139 - accuracy: 0.7958
Epoch 2/200
8000/8000 [==============================] - 0s 41us/step - loss: 0.4586 - accuracy: 0.7958
Epoch 3/200
8000/8000 [==============================] - 0s 39us/step - loss: 0.4393 - accuracy: 0.7977
Epoch 4/200
8000/8000 [==============================] - 0s 49us/step - loss: 0.4265 - accuracy: 0.8089
Epoch 5/200
8000/8000 [==============================] - 0s 43us/step - loss: 0.4080 - accuracy: 0.8241
Epoch 6/200
8000/8000 [==============================] - 0s 41us/step - loss: 0.3900 - accuracy: 0.8359
Epoch 7/200
8000/8000 [==============================] - 0s 40us/step - loss: 0.3763 - accuracy: 0.8450
Epoch 8/200
8000/8000 [==============================] - 0s 43us/step - loss: 0.3694 - accuracy: 0.8493
Epoch 9/200
8000/8000 [==============================] - 0s 42us/step - loss: 0.3650 - accuracy: 0.8505
Epoch 10/200
8000/8000 [==============================] - 0s 48u

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred, y_test)
print(cm)

[[1513  190]
 [  84  213]]
